opt_in_rules: # some rules are only opt-in
  - empty_count
  - redundant_nil_coalescing
  - switch_case_on_newline
  - conditional_returns_on_newline
  - closure_spacing
  - implicitly_unwrapped_optional
  - sorted_imports
  - valid_docs
  - nslocalizedstring_require_bundle

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - nesting
  - identifier_name
  - file_length
  - force_cast
  - nsobject_prefer_isequal
  - conditional_returns_on_newline
  - switch_case_on_newline
  - trailing_comma

included:
  - Sources

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests
  - Pods
  - Carthage
  - Example

# Customizable Rules
cyclomatic_complexity:
  ignores_case_statements: true
